# Generated by Django 3.1 on 2020-08-31 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20200901_0148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eatingaction',
            options={'ordering': ('-time_moment',), 'verbose_name': 'прием пищи', 'verbose_name_plural': 'приемы пищи'},
        ),
        migrations.RenameField(
            model_name='eatingaction',
            old_name='date',
            new_name='time_moment',
        ),
    ]
